### ISSUE TITLE
codec support isn't full

### ISSUE THREAD

**Issue by vankasteelj** [iteufel/nwjs-ffmpeg-prebuilt#1]
Hi, 

I tried your prebuilt libs, we used to have our own for 0.12.

But I encountered two issues:
1) HEVC has no image, only sound support
2) AVI files (probably mpeg2?) have no support at all

Is that normal behavior?

**Comment by iteufel** [comment]
The supported formats should be the same as in Chrome.

**Comment by vankasteelj** [comment]
oh, ok. Then it's normal behavior. Chrome supports not much. Not enough for a desktop app

**Comment by vankasteelj** [comment]
I'm trying to build it myself, to add broader codecs, but without success. It errors all the way because of python being in ascii instead of utf8, so the only way around it I found was to change the scripts called by `gclient runhooks` with an additionnal line for `sys.setdefaultencoding('utf8')`, but it still errors out because of multiple "Resource id not set"

And if I try to ninja, it warns me that there's no `build.ninja` file, and fails immediately.

**Comment by vankasteelj** [comment]
Would you maybe like to help us on the compilation of ffmpeg for https://github.com/butterproject/butter-desktop? We have a list of custom patches that were used on 0.12.2 to add support for almost all video files out there, and we'd like to move on to 0.13 to maybe avoid a painful switch to wcjs.

**Comment by vankasteelj** [comment]
Here are my progresses: https://github.com/butterproject/butter-desktop/issues/339#issuecomment-203573198

**Comment by vankasteelj** [comment]
avi seems really a no-go. It might be possible if someone knows C.
