### ISSUE TITLE
fix macOS build action

### ISSUE THREAD

**Issue by zkrige** [iteufel/nwjs-ffmpeg-prebuilt#109]
Currently GitHub has made macOS runners private - https://github.com/actions/virtual-environments/issues/2486

we would need to build a docker image to do a macOS build

**Comment by iteufel** [comment]
According to the [Chromium guide](https://chromium.googlesource.com/chromium/src/+/master/docs/mac_build_instructions.md), 10.15.4+ should also work.

**Comment by zkrige** [comment]
@iteufel it looks like macOS build is working now. can we close this issue

**Comment by zkrige** [comment]
This is working now
