### ISSUE TITLE
nwjs 0.61.0

### ISSUE THREAD

**Issue by zkrige** [iteufel/nwjs-ffmpeg-prebuilt#132]
Sorry for the dumb question - how do I trigger a new build for the latest nwjs?

**Comment by zkrige** [comment]
@iteufel - the 0.61.0 release is missing assets

**Comment by zkrige** [comment]
@iteufel could you help us out here?

**Comment by DestroyTargetNonBasicLand** [comment]
Looks like the windows dll's failed to build: https://github.com/iteufel/nwjs-ffmpeg-prebuilt/actions/runs/1812496226

**Comment by zkrige** [comment]
fixed and issued new builds
