### ISSUE TITLE
Building FFmpeg for Windows with proprietary codecs

### ISSUE THREAD

**Issue by team-pct** [iteufel/nwjs-ffmpeg-prebuilt#15]
I was able to build for all OS except windows any better method ( With Proprietary codec true )

**Comment by vzamanillo** [comment]
Could you please share the python trace back?

**Comment by vzamanillo** [comment]
@iteufel are you experiencing problems with the latest commit building on Windows?

**Comment by team-pct** [comment]
@vzamanillo i was able to build Windows X64 Nwjs ( with normal ffmpeg)  X86 i will try today 
But Ffmpeg i was unable at all , so far i was able to exec the build_ffmpeg on cygwin but i am getting a weird errors like LIBCMT.lib is missing

**Comment by vzamanillo** [comment]
I am testing the ffmpeg windows build with proprietary codecs right now, I'll let you know.

**Comment by vzamanillo** [comment]
It is very difficult to make this work, I could do a manual configuration with VS2015 and msys2 but requires a lot of tweaks in the chromium configuration script on `third_party/ffmpeg/chromium/scripts/build_ffmpeg.py` so I think I will try with CygWin again.

A very important question is that the needed dev dependencies are missing, should be in `src/third_party/ffmpeg/chromium/include/win` so we have to put it manually.

For reference https://trac.ffmpeg.org/wiki/CompilationGuide

I need to reorganize all steps and try to automate it.

**Comment by vzamanillo** [comment]
@team-pct Could you please test your Nwjs build (for x64) with the attached ffmpeg library with AC3 support (for 0.18.1)?

[ffmpeg.zip](https://github.com/iteufel/nwjs-ffmpeg-prebuilt/files/544485/ffmpeg.zip)

**Comment by team-pct** [comment]
Working just fine !  ( missing AVI )
you can try yourself http://get.popcorntime.sh/repo/nw/v0.18.1/

We miss only win32 NWJS + ffmpeg for WIN32

**Comment by vzamanillo** [comment]
@team-pct Thank you very much for testing!

I am still working in the script for the ia32 version.

I will do a review for AVI support too, I'll keep you informed.

**Comment by vzamanillo** [comment]
[Building on Windows with proprietary codecs](https://github.com/iteufel/nwjs-ffmpeg-prebuilt/blob/master/guides/build_windows.md#build-ffmpegdll-with-proprietary-codecs)

Now everyone can build FFmpeg with proprietary codecs on Windows with the script.

**Comment by team-pct** [comment]
@vzamanillo i was not able to build nwjs for win32 any luck on your side? 
I tried those args  

> gn gen out/nw --args='is_debug=false is_component_ffmpeg=true target_cpu="x86" nwjs_sdk=true enable_nacl=false ffmpeg_branding="Chrome" proprietary_codecs=true enable_ac3_eac3_audio_demuxing=true enable_hevc_demuxing=true is_official_build=true enable_mse_mpeg2ts_stream_parser=true'

**Comment by vzamanillo** [comment]
Unresolved externals?  I was not able to build too with mse_mpeg2ts

**Comment by team-pct** [comment]
It stop on Bluetooth files after 17000 files compiled

**Comment by vzamanillo** [comment]
Oh my god... 

Could you please paste the output log?

**Comment by vzamanillo** [comment]
@team-pct maybe this will be useful https://groups.google.com/a/chromium.org/forum/m/#!topic/chromium-dev/wss2Z0CyMDs

**Comment by team-pct** [comment]
Windows 10 SDK ok ! 
I will start another VPS and compile and let you know thank you for your help ! really appreciate it

**Comment by vzamanillo** [comment]
You are welcome :)

**Comment by wallydz** [comment]
https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/166 Includes a new NWJS + your FFMPEG

**Comment by team-pct** [comment]
https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/166 Includes a new NWJS + your FFMPEG
