### ISSUE TITLE
[Suggestion] Make a Multi OS ffmpeg_generated.gni

### ISSUE THREAD

**Issue by wallydz** [iteufel/nwjs-ffmpeg-prebuilt#17]
Hello,

Why not make it this way?

Every nwjs version have its own branch + instead of compiling and let the user / other coders fight with Compiling why not include Ffmpeg_generated.gni for all the OS ready + chromium/config/Chrome for all OS which will make the work really easier , we wont need build_ffmpeg.py anymore

**Comment by vzamanillo** [comment]
The actual implementation to build FFmpeg with proprietary codecs generates the configuration and builds the library as Google does, with the `build_ffmpeg.py` script it is easy to configure and build the library by everyone, with the default or custom configuration.

If I am understanding your suggestion correctly, someone (me, or iteufel) should generate the configuration for every NWjs version manually and submit it to this repo to be available for everyone, that's a lot of work and we should mantain it (manually).

Ideally we should have a build bot for both FFmpeg prebuilt binaries (with and without proprietary codecs) and publish the new releases automatically to be available for direct downloads for everyone, but we need the server first (multi-arch) and a very good work to configure it, that is the real good way to do.
