### ISSUE TITLE
Question: Support for matroska?

### ISSUE THREAD

**Issue by amilajack** [iteufel/nwjs-ffmpeg-prebuilt#2]
Does this support this `ogg,matroska,wav` demuxers and the `theora,vorbis,vp8,pcm_u8,pcm_s16le,pcm_s24le,pcm_f32le,pcm_s16be,pcm_s24be` codecs? I couldn't find a list in the readme of what this project supports.

**Comment by iteufel** [comment]
@amilajack  The supported formats are

- decoder: vorbis, pcm_u8,pcm_s16le, pcm_s24le, pcm_s32le, pcm_f32le, pcm_s16be, pcm_s24be, pcm_mulaw, pcm_alaw, theora, vp8, aac, h264, mp3

- demuxer: ogg, matroska, wav, aac, mp3, mov

- parser: opus, vorbis, vp3, vp8, aac, h264, mpegaudio

You can find the config files [here](https://chromium.googlesource.com/chromium/third_party/ffmpeg/+/master/chromium/config/Chrome).

**Comment by amilajack** [comment]
Thanks!
