### ISSUE TITLE
Use --proprietary_codecs for prebuilt binaries?

### ISSUE THREAD

**Issue by Kagami** [iteufel/nwjs-ffmpeg-prebuilt#20]
Hi.

As far as I can understand, you don't enable `-pc` flag for your prebuilt binaries, only MP3, AAC and H.264 are available in addition to roality-free formats (i.e. formats like H.265, AC3, MPEG-2 won't work). So my question is: is there any reason for this, and do you plan to release binaries with that configure patch applied?

Thanks.

**Comment by vzamanillo** [comment]
Hi!

from the [Chromium credits](https://chromium.googlesource.com/chromium/third_party/ffmpeg.git/+/master/CREDITS.chromium)

> ...if you enable any of these libraries the resulting binary will
> be under a complex license mix that is more restrictive than the LGPL and that
> may result in additional obligations. It is possible that these
> restrictions cause the resulting binary to be unredistributeable...

we simply offer the posibility to build a custom library to everyone but we can not do prebuilt a library with proprietary codecs due to possible license problems or obligations... sorry.

**Comment by Kagami** [comment]
Are you sure `--enable-nonfree` is required for that flags in the patch? Grep on ffmpeg's `configure` gives:

```
$ grep nonfree configure
  --enable-nonfree         allow use of nonfree code, the resulting libs
    nonfree
die_license_disabled nonfree cuda
die_license_disabled nonfree cuvid
die_license_disabled nonfree libnpp
enabled gpl && die_license_disabled_gpl nonfree libfdk_aac
enabled gpl && die_license_disabled_gpl nonfree openssl
if enabled nonfree; then
    license="nonfree and unredistributable"
```

Only some encoders, cuda and similar stuff.

**Comment by vzamanillo** [comment]
Maybe is not required, I followed the Chromium instructions

> The Fraunhofer AAC library and FAAC are under licenses which
> are incompatible with the GPLv2 and v3. We do not know for certain if their
> licenses are compatible with the LGPL.
> If you wish to enable these libraries, pass `--enable-nonfree` to configure.

But I am not really sure about the flag scope.

**Comment by Kagami** [comment]
Fraunhofer AAC library and FAAC are AAC encoders. You don't need them for decoding (well, technically you can use libfdk for decoding too but ffmpeg has its own AAC decoder under LGPL).

**Comment by vzamanillo** [comment]
So definitely we don't need the flag, then should be removed.

Could you please check the patches and give us any recommendation?

Thank you very much!

**Comment by Kagami** [comment]
I think it's ok otherwise.

**Comment by vzamanillo** [comment]
Thank you very much Kagami!
