### ISSUE TITLE
How should I use "prebuilt binaries"?

### ISSUE THREAD

**Issue by pro200** [iteufel/nwjs-ffmpeg-prebuilt#24]
I just replace "nwjs.app/Contents/Versions/<chromium-version>/nwjs Framework.framework/libffmpeg.dylib" to "prebuilt binary"

and  I used it like this, but it does not work.
```
<video width="320" height="240" controls>
  <source src="video.mkv" type="video/matroska">
</video>
```

**Comment by vzamanillo** [comment]
Hi pro200.

Is not than simple, you need a custom build of NW.js (with proprietary codecs support) enabling extra demuxers and parsers to make it work, replacing the library is not enought.
