### ISSUE TITLE
nwjs build args to enable ac3 and hevc demuxing

### ISSUE THREAD

**Issue by smolleyes** [iteufel/nwjs-ffmpeg-prebuilt#26]
hello

i used your script to build libffmpeg.so against nw 0.19.1 but i need to build nwjs with proprietary codec

so i did it with 

gn gen //out/nw  --args='is_debug=false is_component_ffmpeg=true target_cpu="x64" is_official_build=true ffmpeg_branding="Chrome" enable_nacl=true proprietary_codecs=true'

and nothing black screen on avi / ac3 not oworking etc

i tried with chromeOS as ffmpeg branding and avi works but very choppy and ac3 not working.. so how do you build your nw to get hevc / ac3 etc working please?

thanks

**Comment by vzamanillo** [comment]
Hi @smolleyes !!

enabling the proprietary codecs interfaces is not enought, try adding

`proprietary_codecs=true enable_ac3_eac3_audio_demuxing=true enable_hevc_demuxing=true`

**Comment by smolleyes** [comment]
hello vzamanillo

yup seems working for ac3 but if i keep Chrome as ffmpeg_branding it does not decode avi files... with chromeOS it works but very bad decoding with "low" resolution file in nw 0.19.1 same thing for a 360p video from youtube (so mp4 or vp9) very strange

:(

**Comment by vzamanillo** [comment]
@smolleyes, thank you very much, dts/dtsh support should be great.

I have to do some changes related to patching on 19.x and test the build procedure on the common platforms again, my last builds did not give problems for the 18.x branch.

Related to AVI, I do not what the problem could be, but I don't think is directly related with Chrome, it's more about ffmpeg.

**Comment by smolleyes** [comment]
hello

i ll add dtshd now and will try for wmv/a, to fix the problem with avi and chrome you just have to remove the '--disable-error-resilience' and it works but suck as ususal image is very slow and like "checking" strange... i ll keep my live transcoding for avi...

BRB for dtshd, ac3-dts seems already working :p

**Comment by smolleyes** [comment]
very strange , many avi files works normally ... can t see any difference thru chrome://media-internals :/

**Comment by vzamanillo** [comment]
@smolleyes, great! Good news! 
Could you please post your changes (or do a PR)? 

Thank you very much for your contribution!

**Comment by smolleyes** [comment]
hello

no success for the moment will continue to work on this...

gclient or git clone is boring... too slow!!!!!!! 

: Cloning Chromium source code for nw-0.19.2 in /opt/nwjs_build/build_dir/ffmpeg/nwjs-ffmpeg-prebuilt/build
Clonage dans 'src'...
remote: Counting objects: 228748, done.
remote: Compressing objects: 100% (176159/176159), done.
Réception d'objets:  35% (82110/228748), 253.38 MiB | **120.00 KiB/s**

i have a 1 GB/s connexion!!! have the same problem ? 

thanks

**Comment by smolleyes** [comment]
do you have an updated process to build on windows ? (wich vs / cygwin etc...) i made it with nwjs 0.7.3 a long time ago  and don t remember the process :p 

thanks ;)

**Comment by vzamanillo** [comment]
Not yet, sorry, the real life is too expensive about time. I will take a look, don't worry.

**Comment by smolleyes** [comment]
ahah i agree ;) np, thanks

**Comment by vzamanillo** [comment]
The patch for building on windows has been updated for 19.x, but not all are good news, I am getting errors with asm when compiling the object code (with x64, I did not test with ia32)

`../../third_party/ffmpeg/libavcodec/x86/vp8dsp_loopfilter.asm:1584: error: invalid size for operand 1`

**Comment by vzamanillo** [comment]
> BRB for dtshd, ac3-dts seems already working :p

@smolleyes, is `dts` working? could you please do a PR or post your changes for `dts` support? I would like to include it for future patches.
