### ISSUE TITLE
[question] Is the python builder dependent on NWJS version?

### ISSUE THREAD

**Issue by Yonezpt** [iteufel/nwjs-ffmpeg-prebuilt#3]
I have been trying to understand if the ffmpeg.dll builder depends on the NWJS versions or just Chromium releases, but I cannot find a clear indication of this. My concern is related to building a binary that is for an old NWJS version that is no longer compatible with any future release, but if this is only depending on Chromium releases then it won't matter which is the latest NWJS version, unless Chrome changes the .dll like they did before, but that's a different situation from this one.

**Comment by iteufel** [comment]
The builder is using the nwjs fork of chromium https://github.com/nwjs/chromium.src to build the dlls. 
You can use `--nw_version` to set the nwjs branch (13, 14, 14, 16).

But can't build nw17 dlls with the current version because nw17 is using GN instead of GYP.
But i'm working on it. 😎

**Comment by Yonezpt** [comment]
Ahh, I see now: https://github.com/iteufel/nwjs-ffmpeg-prebuilt/blob/master/build_ffmpeg.py#L48

So for now the current instructions in your repo will not work for building a ffmpeg for NWJS17?

Also noticed the NWJS documentation is still using GYP for build instructions of the ffmpeg: http://docs.nwjs.io/en/latest/For%20Developers/Enable%20Proprietary%20Codecs

Shouldn't these be updated to include instructions for GN instead of GYP? I know you have nothing to do with that, but I wanted to be sure of this before asking them to update their wiki.
