### ISSUE TITLE
Building with proprietary_codecs doesn't play avi files.

### ISSUE THREAD

**Issue by blaremc** [iteufel/nwjs-ffmpeg-prebuilt#32]
Hello!

I built library with flag -pc and without it. A sizes of .dylib are 4.2 MB and 2.6 MB respectively. Without any codecs the size of this library in original nwjs is 1.3 MB.
But there are not difference between 4.2 MB and 2.6 MB. It works the same.

OS X El Capitan 10.11.6
nwjs 19.4

**Comment by vzamanillo** [comment]
You need a custom build of NW.js (with proprietary codecs support) enabling extra demuxers and parsers to make it work, replacing the library is not enough.

**Comment by blaremc** [comment]
@vzamanillo and if i build only ffmpeg dll like this http://docs.nwjs.io/en/latest/For%20Developers/Enable%20Proprietary%20Codecs/#build-ffmpeg-dll-without-building-nwjs i couldn't play avi? 
Or I need to build nwjs completely like this http://docs.nwjs.io/en/latest/For%20Developers/Enable%20Proprietary%20Codecs/#build-entire-nwjs-with-proprietary-codecs

**Comment by LukasBombach** [comment]
First of all thank you for this awesome project.

+1 on this question though. What would it take to play XVID and other commonly used codecs and formats?
