### ISSUE TITLE
Linux builds missing from releases

### ISSUE THREAD

**Issue by jmx** [iteufel/nwjs-ffmpeg-prebuilt#34]
Hi there - I've found this project useful for automating my integration of working ffmpeg with nwjs, however I've noticed for the last version (21.x) there are no longer linux 32 or 64 bit builds?

Is this an issue with your build system or are you no longer going to produce ffmpeg binaries for linux?

**Comment by iteufel** [comment]
@jmx Linux builds are now working again.
