### ISSUE TITLE
0.23.0 release fails on Win 10  (win-ia32 and win-x64) with nw.js0.23.0

### ISSUE THREAD

**Issue by notsospecial1** [iteufel/nwjs-ffmpeg-prebuilt#36]
Entry Point Not Found

The procedure entry point av_sterror could not be located in the dynamic link library

... \nw.dll

**Comment by iteufel** [comment]
@notsospecial1 thanks, i will fix the release.

**Comment by yoko10000** [comment]
me too

**Comment by iteufel** [comment]
The release is fixed.
