### ISSUE TITLE
[Question] Can I use nwjs-ffmpeg-prebuilt binary and distribute in a commercial app?

### ISSUE THREAD

**Issue by Ajeey** [iteufel/nwjs-ffmpeg-prebuilt#38]
Hi,

Can I use the nwjs-ffmpeg-prebuilt binaries and distribute in my nwjs app which is for commercial use?

**Comment by iteufel** [comment]
Using the H.264 codec requires you to pay attention to the patent royalties and the license of the source code. Consult a lawyer if you do not understand the licensing constraints and using patented media formats in your application. For more information about the license of the source code, check [here](https://chromium.googlesource.com/chromium/third_party/ffmpeg.git/+/master/CREDITS.chromium).
