### ISSUE TITLE
Update build steps for nw 0.17.0 with GN tool

### ISSUE THREAD

**Issue by ghostoy** [iteufel/nwjs-ffmpeg-prebuilt#4]
@iteufel We started to use GN tool to build NW.js since 0.17.0. The new instruction is in here nwjs/nw.js#5272.

**Comment by iteufel** [comment]
@ghostoy thanks for the update but i have problems building it on osx

> ERROR at //third_party/ffmpeg/BUILD.gn:204:18: Item not found
    configs -= [ "//build/config/compiler:default_stack_frames" ]
                 ^---------------------------------------------
You were trying to remove "//build/config/compiler:default_stack_frames"
from the list but it wasn't there.
See //BUILD.gn:3:9: which caused the file to be included.
        "//third_party/ffmpeg"
        ^---------------------

**Comment by ghostoy** [comment]
@iteufel The steps works on my mac. The error is caused by you checked out at a wrong commit. The commit of ffmpeg works with nw17 is `d45f90eac6d5eb22be6120b1f7cb145f7a7c88b0`. And the dependency to the config was introduced in `35740fc7b72ac1d9adff69e67f3f61b639484dc3`, which is beyond the required commit.

It should be caused by a misuse of `-o` option with `git clone` in your `build_ffmpeg.py` script. `-o` doesn't do what you meant to do in your script.

> --origin <name>
-o <name>
Instead of using the remote name origin to keep track of the upstream repository, use <name>.

There is no easy way to simply checkout at a commit with git clone especially when you want a shallow clone. You can refer to how `depot tools` achieves this by using `--template` (see https://chromium.googlesource.com/chromium/tools/depot_tools/+/master/gclient_scm.py#940).

The simplest way may be to recreate `DEPS` with minimal `deps` and `hooks`, and use `gclient sync --no-history` to let it do all the rest.
