### ISSUE TITLE
No 0.24.0-win-ia32.zip file

### ISSUE THREAD

**Issue by Pabloandumundu** [iteufel/nwjs-ffmpeg-prebuilt#40]
Some kind of fault when you published:

There is no 0.24.0-win-ia32.zip file.
There is a file with name 0.24.0-win-x86.zip that is equal to 0.24.0-win-x64.zip

**Comment by iteufel** [comment]
@Pabloandumundu  i will fix it.

**Comment by Pabloandumundu** [comment]
thanks!

**Comment by phpjishu** [comment]
Or no 0.24.0-win-ia32.zip?

**Comment by phpjishu** [comment]
Or no 0.24.0-win-ia32.zip? @iteufel

**Comment by iteufel** [comment]
Is fixed.
