### ISSUE TITLE
Build Error : Help

### ISSUE THREAD

**Issue by xcholar** [iteufel/nwjs-ffmpeg-prebuilt#47]
I have cloned your repo and trying to build it via

python build_ffmpeg.py --target=x64

And I am getting the following error, I need your help, please!
-------------------------------------------------------------------------------
![default](https://user-images.githubusercontent.com/28098513/32669469-9ea37144-c67b-11e7-951a-1c08988eec88.png)

**Comment by iteufel** [comment]
Should be fixed now.
