### ISSUE TITLE
Automate builds

### ISSUE THREAD

**Issue by Asp3ctus** [iteufel/nwjs-ffmpeg-prebuilt#48]
NW.js is releasing releases fast now days.
And builds here are posted much later

**Comment by sparkyb** [comment]
I agree. I don't mind waiting a little bit, but it's been over a month since NW.js 0.27 came out and there's still no ffmpeg prebuilt for any 0.27 version. Is this defunct, or are they still coming?

**Comment by yoko10000** [comment]
I agree.

**Comment by MilenFrom** [comment]
I assume they're still coming.
I hope this year will have more time, I would like to help iteufel.

**Comment by iteufel** [comment]
I have now Automated the builds on all platforms using Jenkins.

**Comment by Asp3ctus** [comment]
Linux build still not available, will it be posted later ?

**Comment by Extarys** [comment]
YAY! With the automated build process, in how long can we expect the 0.28.0 binaries for linux? :D

**Comment by Asp3ctus** [comment]
i guess we need to close this issue

**Comment by gpetrov** [comment]
@iteufel  where can we find the automated builds? As with the release I only see the 0.28.0 while 0.28.1 is already release few days ago.

Also do you think we can integrate them with tools like nwbuilder so they can be auto downloaded during the packaging?

**Comment by Asp3ctus** [comment]
> i guess we need to close this issue
or not.

@iteufel can you please share wherewe can find fresh builds?

**Comment by Asp3ctus** [comment]
Any update on this?
I have tried to make a fork and build it via travis ci but with no luck... also it didn't build on local linux setup..
It would be nice to update to new versions of nwjs

**Comment by Asp3ctus** [comment]
@iteufel thank you for update !!!
I will try to see how you did it, maybe i can be some help.

**Comment by zkrige** [comment]
Is there anything I can do to help with automated builds?

**Comment by iteufel** [comment]
I have now automate the builds using GitHub Actions.

**Comment by zkrige** [comment]
wow - fantastic - thank you so much
