### ISSUE TITLE
0.28.0 linux not working

### ISSUE THREAD

**Issue by smolleyes** [iteufel/nwjs-ffmpeg-prebuilt#50]
hi

just tried lastest .so with nwjs 0.28.0 (x64) and .1, nwjs won t decode anything, 0.28.1 coming soon ?

thanks m8

**Comment by iteufel** [comment]
@smolleyes 0.28.1 is here.
I had some trouble on Linux x86 (https://bugs.chromium.org/p/chromium/issues/detail?id=796379).
