### ISSUE TITLE
how to use libffmpeg.so 

### ISSUE THREAD

**Issue by georgerizescu** [iteufel/nwjs-ffmpeg-prebuilt#52]
i want to be able to play mp4 video/audio in my nwjs app on linux. i did this:
1. download nwjs 28.1 for linux from nwjs.io https://dl.nwjs.io/v0.28.1/nwjs-v0.28.1-linux-x64.tar.gz
2. download https://github.com/iteufel/nwjs-ffmpeg-prebuilt/releases/download/0.28.1/0.28.1-linux-x64.zip and extract libffmpeg.so to /lib in nwjs directory
yet, my app doesn’t play video or audio.
what i do wrong?

i get these errors in my log
"Uncaught (in promise) NotSupportedError: Failed to load because no supported source was found.", source

**Comment by iteufel** [comment]
@georgerizescu I have tested it on mint 18.3.
Can you provide me with more informations (distribution, version, …).

**Comment by georgerizescu** [comment]
thank you for your fast reply. 
i can confirm that is working, the problem was with the app itself (no acces for that server to the mp4 content). nwjw is version 0.28.1 and lib also version 0.28.1 running on linux centos 7.
