### ISSUE TITLE
Linux broken?

### ISSUE THREAD

**Issue by smolleyes** [iteufel/nwjs-ffmpeg-prebuilt#53]
hi

spend few hours yesterday to build the 0.28.3 linux ffmpeg.so and have some difficulties:

deps are not installed, had to figure i needed ninja-build/clang/ldd/fuse-dev libavcodec-dev etc etc, then the patch for the -pc option is not working anymore had to change it (will provide pr if possible)

BUT the biggest problem is i ended with a 16.6 mo .so file without build error, but nwjs 0.28.3 won t play anything but vp8/9 and mp3 , no aac, no h264,  no hevc (dont care about others) have the same problem ? (demuxer problem can t open...)

**Comment by smolleyes** [comment]
hello

so.. finally i forked the butter project nwjs build script, fixed it and rebuilded a full nwjs with ffmpeg full codecs... play barely everything :)

updated build script here:
https://github.com/smolleyes/nwjs-build/blob/master/build_linux64.sh

and resulting nwjs 0.29.1 sdk linux-64 build here (builded on ubuntu 17.10, not tested on 16.04)
http://163.172.88.44/nwjs-builds/linux/64/nwjs_0.29.1_sdk_linux-64.zip

++

**Comment by iteufel** [comment]
If the issue still exists just write it down and I will reopen the issue.
