### ISSUE TITLE
[Question] confused if I need the rebuilt fmpeg.dll anymore

### ISSUE THREAD

**Issue by MaherFa** [iteufel/nwjs-ffmpeg-prebuilt#54]
I recently updated to NWJS 0.29.1 (win-x64) and started running some tests and I was surprised it was able to play MP3 files without me downloading the rebuilt ffmpeg

I came here and downloaded it anyway and it was just a little bit smaller in size than the one shipped with NWJS
so, now I'm confused! do we no longer need to download the rebuild ffmpeg or what, and what are the differences between the two?

**Comment by iteufel** [comment]
### In the pre-built NW.js, the following codecs are supported:
- theora
- vorbis
- vp8 & vp9
- pcm_u8, pcm_s16le, pcm_s24le, pcm_f32le, pcm_s16be & pcm_s24be
- mp3 (v0.22.1+)

###  nwjs-ffmpeg-prebuilt adds support for following formats
- aac
- h264

**Comment by MaherFa** [comment]
> mp3 (v0.22.1+)
this explains it all, thank you so much
