### ISSUE TITLE
Build needed for 0.30.0

### ISSUE THREAD

**Issue by kevinwright** [iteufel/nwjs-ffmpeg-prebuilt#56]
The title says it all!

**Comment by yoko10000** [comment]
0.30.0-osx-x64.zip压缩包里是libffmpeg.dylib文件，不是ffmpeg.dll呢，麻烦请看一下，好吗？！谢谢！

**Comment by luffs** [comment]
Any plans of building the 0.30.0 binaries for Windows? Were there problems with building them?
It would be really appreciated!

**Comment by frankhale** [comment]
Currently missing build for Windows. Are there currently issues which are causing it not to build?

**Comment by iteufel** [comment]
Sorry for the late builds.
I had some problems switching to VS2017.

**Comment by frankhale** [comment]
THANK YOU!
