### ISSUE TITLE
From 28 no running with H264

### ISSUE THREAD

**Issue by kkm** [iteufel/nwjs-ffmpeg-prebuilt#57]
MediaRecorder and Webrtc dont work anymore in H264 encoder and decoder.
https://github.com/nwjs/nw.js/issues/6569

**Comment by iteufel** [comment]
@kkm It seams that the build flag [RTC_USE_H264](https://github.com/nwjs/chromium.src/blob/nw30/content/renderer/media_recorder/video_track_recorder.cc#L33) is not set anymore.
WebRTC should work without FFmpeg it's using [openh264](https://github.com/nwjs/chromium.src/blob/45be0261c5a04cc38dead115740a8a6f7e6958a7/content/renderer/media_recorder/h264_encoder.cc#L13).

**Comment by kkm** [comment]
Okay but I did try with open264 but it doesnt work. how can I set for SDP in H264?
Are you sure that WebRTC uses openh264? in Firefox works well with H264.

**Comment by kkm** [comment]
https://github.com/nwjs/nw.js/issues/6569
