### ISSUE TITLE
nwjs 0.30.3 crashes on windows

### ISSUE THREAD

**Issue by izure1** [iteufel/nwjs-ffmpeg-prebuilt#59]
Please understand that I use translator because it is not familiar with English.

I am using windows 10 64bit and build the application using nw-builder.
I also found a problem with version 0.30.2 and version 0.30.3 of ffmpeg.
The application crashes after it is started.

Are you experiencing the same symptoms?

**Comment by frankhale** [comment]
Try using 0.30.5 (latest release today). Also it would be helpful if you posted a link to an example code that is producing this issue.

**Comment by iteufel** [comment]
If the issue still exists just write it down and I will reopen the issue.
