### ISSUE TITLE
Need build for NW.js 0.31.0

### ISSUE THREAD

**Issue by frankhale** [iteufel/nwjs-ffmpeg-prebuilt#63]
The 0.30.5 build doesn't work for NW.js 0.31.0. It would be really nice if there was a new build that would work with it.

**Comment by luca-viggiani** [comment]
Same is for 0.31.1. nwjs crashes as soon as my contents tries to playback any mp3 files (works fine with default shipped ffmpeg)

**Comment by frankhale** [comment]
Thank you for the updated builds!!!
