### ISSUE TITLE
Could you help me to generate a ffmpeg of 0.27.4 version ?

### ISSUE THREAD

**Issue by tangyue0924** [iteufel/nwjs-ffmpeg-prebuilt#65]
Just v0.27.5 can be downloaded...
I really need the ffmpeg of 0.27.4 version..
Thanks a lot...
Need your help~

**Comment by iteufel** [comment]
@tangyue0924  0.27.5 should work fine with 0.27.4

**Comment by tangyue0924** [comment]
> @tangyue0924 0.27.5 should work fine with 0.27.4

Because of the same Chromium version ?

**Comment by iteufel** [comment]
@tangyue0924 most of the time, the binaries should work for all patch versions.

**Comment by iteufel** [comment]
If the issue still exists just write it down and I will reopen the issue.
