### ISSUE TITLE
chromium crashes at startup

### ISSUE THREAD

**Issue by hamid-a** [iteufel/nwjs-ffmpeg-prebuilt#66]
My chromium browser crashes at startup when I replace libffmpeg.so with prebuilt version.

nwjs: nwjs-sdk-v0.32.3-linux-x64
nwjs-ffmpeg-prebuilt: 0.32.3
os: ubuntu 18.04 x64

I also use 0.32.4 version too and there is the similar problem.
Here is the crash dump:
[chromium-extension-minidump.zip](https://github.com/iteufel/nwjs-ffmpeg-prebuilt/files/2384430/chromium-extension-minidump.zip)

**Comment by iteufel** [comment]
@hamid-a please try again with the latest version 0.33.4.
