### ISSUE TITLE
opera - which release version? 

### ISSUE THREAD

**Issue by csonuryilmaz** [iteufel/nwjs-ffmpeg-prebuilt#67]
I'm using Opera version **55.0.2994.61**. My system is;
```
	Debian GNU/Linux 9 (stretch) (x86_64; XFCE)
```
I've downloaded latest version (**0.32.4-linux-x64.zip**), extracted **libffmpeg.so** into */usr/lib/x86_64-linux-gnu/opera* folder. But browser tab crashes when I start playing video.

Which release version is suitable with Opera **55.0.2994.61**?

**Comment by csonuryilmaz** [comment]
Meanwhile after many trials with some *ubuntu* packages, temporarily [chromium-codecs-ffmpeg-extra 69.0.3497.81-0ubuntu0.16.04.1](https://launchpad.net/ubuntu/xenial/amd64/chromium-codecs-ffmpeg-extra/69.0.3497.81-0ubuntu0.16.04.1) worked with my opera version.

**Comment by iteufel** [comment]
@csonuryilmaz you can try 0.33.4 both are using chromium 69

**Comment by csonuryilmaz** [comment]
@iteufel  I've tried release [0.33.4-linux-x64.zip](https://github.com/iteufel/nwjs-ffmpeg-prebuilt/releases/download/0.33.4/0.33.4-linux-x64.zip) **but** page crashes when I open a video.
*uname -a*:
```
Linux minibox 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64 GNU/Linux
```
Crash video is [here](https://www.dropbox.com/s/hr21x9tgpxt09pk/opera-crash.mkv?dl=0)

**Comment by csonuryilmaz** [comment]
@prajnoha I tried release [0.31.5-linux-x64.zip](https://github.com/iteufel/nwjs-ffmpeg-prebuilt/releases/download/0.31.5/0.31.5-linux-x64.zip) and it definetly works. Thanks a lot.
