### ISSUE TITLE
latest binaries crash nwjs

### ISSUE THREAD

**Issue by asteriosgr** [iteufel/nwjs-ffmpeg-prebuilt#70]
On versions 0.33.2 and 0.33.4 (these are the ones I tested), pre-compiled binaries and manual compiled binaries are crashing the nwjs. Am I the only one experiencing this issue?

**Comment by skaughtx0r** [comment]
I am also experiencing this. The last working version for me is 0.31.5.
All of the 0.32 and 0.33 binaries crash as soon as I try to append to the sourceBuffer.

I'm stuck in a bad spot right now because I need OffscreenCanvas support and it only started working in 0.32

**Comment by skaughtx0r** [comment]
I've only tested on Ubuntu 16.04

**Comment by choukui** [comment]
I encountered the same problem.

**Comment by Bluesboy** [comment]
Opera browser on Fedora 29 crashes with 0.33.4 and 0.34.0 versions, rolled back to 0.31.2 everything works fine.

**Comment by comcon1** [comment]
Opera browser on OpenSuse Leap 15.0 crashes with versions 0.34.0 and 0.26.6.

**Comment by ItachiSan** [comment]
I have the same issue, this when using PopcornTime.

To reproduce, build PopcornTime on a 64-bit Linux in this way:

1. (*One-time*) Download the source code using Git from:
https://github.com/popcorn-official/popcorn-desktop/
2. (*One-time*) I assume you have a working Node.js setup. If not, set it up accordingly.
3. (*One-time*) If you don't have *yarn* installed, install it using
`npm install yarn`
4. Adjust the `nwVersion` variable to your desired NW.js version
5. `yarn install`
6. `yarn build`
7. `yarn gulp run`

All the Linux builds newer than `0.31.5` will fail to work, crashing the app.
All the Windows build do work instead.

*Notice*: all the builds use the SDK flavour.

**Comment by iteufel** [comment]
@ItachiSan 0.35.2 should work on Linux.

**Comment by ItachiSan** [comment]
@iteufel it does! What was the issue?
