### ISSUE TITLE
Need build for NW.js 0.36.4 

### ISSUE THREAD

**Issue by yoko10000** [iteufel/nwjs-ffmpeg-prebuilt#73]
could you please release the binaries for the current NW.js 0.36.4?thanks!

**Comment by iteufel** [comment]
@yoko10000 I will try to Release new Builds mid next week.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by yoko10000** [comment]
thank you very munch！

**Comment by hthetiot** [comment]
Thank you.

**Comment by chatcan** [comment]
Thank you

**Comment by hthetiot** [comment]
I think it's better to go Chromium 73 aka nwjs 37 directly as  Chromium 71/72 was bad release of chrome (in my point of view).
- https://github.com/nwjs/nw.js/blob/nw37/CHANGELOG.md#0370--03-13-2019

cc @iteufel @yoko10000

**Comment by hthetiot** [comment]
(Fun fact this issue is #73 it's is a sign we should use nw.js 37 ahah)

**Comment by yoko10000** [comment]
oh,nw.js 37.0

**Comment by yoko10000** [comment]
oh,v0.37.1

**Comment by iteufel** [comment]
I have released binaries for 0.37.4. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hthetiot** [comment]
@iteufel Thank you.
