### ISSUE TITLE
Can not build

### ISSUE THREAD

**Issue by kronikpillow** [iteufel/nwjs-ffmpeg-prebuilt#75]
[kronikpillow@susanoo nwjs-ffmpeg-prebuilt]$ sudo python build_ffmpeg.py --target_arch=x64
  File "build_ffmpeg.py", line 104
    print '\n\nShutdown requested... \x1b[0;31;40m' + 'exiting' + '\x1b[0m'
                                                  ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('\n\nShutdown requested... \x1b[0)?
[kronikpillow@susanoo nwjs-ffmpeg-prebuilt]$ 

OS: ArcoLinux I3

dunno if im missing any relevant information

**Comment by SalchiPapa** [comment]
You are using python3 and the script is written for python2. Try again using the python2 runtime:

    $ python2 build_ffmpeg.py --target_arch=x64

The error is telling you it expects:

    >>> print('foo')  # python3 syntax

Instead of:

    >>> print 'foo'  # python2 syntax
