### ISSUE TITLE
Windows Build needed for 0.38.1

### ISSUE THREAD

**Issue by marc7000** [iteufel/nwjs-ffmpeg-prebuilt#76]
Currently missing build for Windows.
Any plans for building the 0.38.1 binaries for Windows?

**Comment by fracland** [comment]
The windows packages will never be built again? that's it ? I wait quietly for several months, but perhaps must I look how to build them myself? tell me, thanks for your answer.
FL

**Comment by iteufel** [comment]
Hi @fracland,  I'm busy with my final exam, but I'm building the windows builds manually this weekend and will try to update the script.

**Comment by fracland** [comment]
Thanks Allan !

**Comment by iteufel** [comment]
@fracland , @marc7000 I have released libs for 0.38.4 https://github.com/iteufel/nwjs-ffmpeg-prebuilt/releases/tag/0.38.4

**Comment by marc7000** [comment]
Thank you Allan!
