### ISSUE TITLE
NW.js 0.39.0 with Chromium 75

### ISSUE THREAD

**Issue by sonicmouse** [iteufel/nwjs-ffmpeg-prebuilt#77]
Hey all...
First off: thanks for taking on the responsibility of compiling these builds in your freetime. A lot of us really appreciate all this work you all do pro bono.

We are in a pinch here. The release you guys just built is for 38.4 which is dependent on Chromium 74. There is a huge rendering bug in 74 and we need to use 75. NW.js just released 0.39.0 which includes 75 which fixes our issue... BUT, we need the FFMPEG library built for 0.39.0.

How long do you all usually wait before build the FFMPEG for newer build of NW? If I buy you a few beers, could you get it done sooner?

Thanks so much for your time.

**Comment by iteufel** [comment]
@sonicmouse I'm trying to release new builds tomorrow.

**Comment by iteufel** [comment]
@sonicmouse I have just released the new versions.

**Comment by sonicmouse** [comment]
whoa thanks!
My team is going to be super happy... From all of us over here: thank you for helping us out.
