### ISSUE TITLE
win build error

### ISSUE THREAD

**Issue by infantilo** [iteufel/nwjs-ffmpeg-prebuilt#78]
we are getting the following error trying to compile for win:
`INFO: Setting nw version to 0.33.3
INFO: Building ffmpeg for 0.33.3 on win for x64, proprietary_codecs = False
Creating C:\Users\thoma\Desktop\nwjs-ffmpeg-prebuilt-master\build directory...
WARNING: C:\Users\thoma\Desktop\nwjs-ffmpeg-prebuilt-master\build directory already exists, skipping...
INFO: Cleaning output directory...
INFO: Creating .gclient file...
INFO: Cloning Chromium source code for nw-0.33.3 in C:\Users\thoma\Desktop\nwjs-ffmpeg-prebuilt-master\build
INFO: Hard source code reset to nw 0.33.3 specified version
INFO: Cleaning previous DEPS and BUILD.gn backup files...
INFO: Backing up and overwriting DEPS...
INFO: Backing up and overwriting BUILD.gn...
INFO: Syncing with gclient...
INFO: Generating ninja files...
ERROR: Traceback (most recent call last):
  File "build_ffmpeg.py", line 103, in main
    build(target_cpu)
  File "build_ffmpeg.py", line 447, in build
    subprocess.check_call('gn gen //out/nw "--args=is_debug=false is_component_ffmpeg=true target_cpu=\\\"%s\\\" is_official_build=true ffmpeg_branding=\\\"Chrome\\\""' % target_cpu, shell=True)
  File "C:\Python27\lib\subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'gn gen //out/nw "--args=is_debug=false is_component_ffmpeg=true target_cpu=\"x64\" is_official_build=true ffmpeg_branding=\"Chrome\""' returned non-zero exit status 2
`

Plz give advice!

**Comment by iteufel** [comment]
If the issue still exists just write it down and I will reopen the issue.
