### ISSUE TITLE
Inconsistent release file naming

### ISSUE THREAD

**Issue by mkazlauskas** [iteufel/nwjs-ffmpeg-prebuilt#79]
0.37.4-win-**ia32**.zip
vs
0.38.4-win-**i32**.zip
vs
0.39.2-win-**x86**.zip

This is causing issues with build tooling (specifically I'm using [nwjs-builder-phoenix](https://github.com/evshiron/nwjs-builder-phoenix) which expects arch to be `ia32`

**Comment by iteufel** [comment]
@mkazlauskas Thanks for the information.
I have fixed the names.
