### ISSUE TITLE
NW.js Release 0.40.1

### ISSUE THREAD

**Issue by marc7000** [iteufel/nwjs-ffmpeg-prebuilt#80]
@iteufel do you have release plans for NW.js 0.40.1?

**Comment by iteufel** [comment]
@marc7000 I am currently building the new binaries 😁.

**Comment by marc7000** [comment]
Awesome thank you!

**Comment by zkrige** [comment]
Is there any update on this? Can I do anything to help?

**Comment by marc7000** [comment]
Thank you!
https://github.com/iteufel/nwjs-ffmpeg-prebuilt/releases/tag/0.41.2
