### ISSUE TITLE
 do you have release plans for NW.js 0.41.1?

### ISSUE THREAD

**Issue by yoko10000** [iteufel/nwjs-ffmpeg-prebuilt#82]
do you have release plans for NW.js 0.41.1?

**Comment by zkrige** [comment]
this repo doesnt seem very active - are there any forks that do more regular releases?

**Comment by vzamanillo** [comment]
Remember, if someone urgently needs a binary, can always do a checkout of this repository and build it for itself, making a build without the proprietary codecs it is very easy for any plattform.

**Comment by zkrige** [comment]
thanks @vzamanillo 

what is the disk size footprint? I was under the impression it was huge?

**Comment by vzamanillo** [comment]
Oh, unfortunately, releases since version nw-v0.34.0-beta1 cannot currently be built because of this https://github.com/nwjs/nw.js/issues/6864. As part of the build process this script clones the nwjs chromium source code from the release version tag, this tags does not exists anymore.

We need some script modifications to solve this issue.

**Comment by zkrige** [comment]
gosh - im so annoyed. I wish we'd never gone NWJS. its so mickey mouse. I'm honestly considering rewriting for electron. at least its properly supported.

and before anyone gets upset, I always offer support on a project as a first option for any bugs I report

**Comment by iteufel** [comment]
@zkrige I'm just doing a build of the dlls with the full chromium src.

**Comment by zkrige** [comment]
thanks for the feedback. at this stage we've pinned to an older version of nwjs because newer versions all break different things.

thanks for your support to the nwjs project by doing the ffmpeg builds

**Comment by iteufel** [comment]
@zkrige, @yoko10000 I released the new dlls.
I'm currently working on rewriting the build script to use the official chromium.src.

**Comment by zkrige** [comment]
thank you very much @iteufel 

Please let me know if I can help with anything

**Comment by yoko10000** [comment]
thanks @iteufel
