### ISSUE TITLE
Building Dependencies libcxx

### ISSUE THREAD

**Issue by asteriosgr** [iteufel/nwjs-ffmpeg-prebuilt#85]
I am trying to create a Dockerfile, that can be used for for building ffmpeg in a container. My issue is that when I initiate this (from ubuntu:latest) :
```python build_ffmpeg.py --target_arch=x64 --nw_version=nw42```
I get this:
ERROR: Traceback (most recent call last):
  File "build_ffmpeg.py", line 89, in main
    generate_build_and_deps_files()
  File "build_ffmpeg.py", line 559, in generate_build_and_deps_files
    f.write("%s\n%s\n%s" % (get_min_vars(deps_str), get_min_deps(deps_str), get_min_hooks()))
  File "build_ffmpeg.py", line 316, in get_min_deps
    raise Exception("`%s` is not found in DEPS" % k)
Exception: `libcxx` is not found in DEPS

What I tried:
installing libc++ libc++-dev , it didn't work

**Comment by vahidalizad** [comment]
I have the same problem on nw39 and windows

**Comment by vahidalizad** [comment]
i solved it by changing the `build_ffmpeg.py` file.
Just changed the `ur"libcxx_revision.*\"(.+)\""` to `ur"libcxx_revision.*\'(.+)\'"` and changing `ur"libcxxabi_revision.*\"(.+)\""` to `ur"libcxxabi_revision.*\'(.+)\'"`
