### ISSUE TITLE
NW.js Release 0.43.5

### ISSUE THREAD

**Issue by zkrige** [iteufel/nwjs-ffmpeg-prebuilt#86]
Can you please build for this version?

**Comment by zkrige** [comment]
I would do the builds but I don't have a windows machine available to do the windows builds on

**Comment by iteufel** [comment]
@zkrige I'm working on it right now.

**Comment by zkrige** [comment]
Wow thank you very much!!

Is there some way to setup something that auto builds as soon as new nwjs is released?

**Comment by gpetrov** [comment]
The latest nwjs 0.43.5 seems very stable so having to codecs for it will be great.

@iteufel - maybe you can setup a CI or Github Actions to auto build on each release?

**Comment by zkrige** [comment]
I would assume there's a cost involved for having actions do the build, as you need a windows env and macOS env....

**Comment by iteufel** [comment]
@zkrige I am currently still working on a manual build for all platforms.

I think It would be better to rewrite the build script and use the official chromium src for the libraries.
Then we can also automate it more easily.

**Comment by zkrige** [comment]
thank you for your effort - it is much appreciated

**Comment by gpetrov** [comment]
and now we have 0.43.6 update. Following up quickly. Hope you build the codes directly for it

@iteufel maybe you @rogerwang can help you setup a live build environment, just as he did with nwjs live build.

**Comment by iteufel** [comment]
@zkrige @gpetrov 
I have rewritten the script in node.js
The new version consumes more disk space but should be easier to maintain now.

**Comment by gpetrov** [comment]
Awesome work @iteufel - node script is the way to go for easy building! 

If you can only add also the Linux version :) - then we are complete and go for launch!

**Comment by iteufel** [comment]
@gpetrov I have uploaded the linux versions.

**Comment by zkrige** [comment]
thank you!
