### ISSUE TITLE
No win builds for latest version

### ISSUE THREAD

**Issue by GendelfLugansk** [iteufel/nwjs-ffmpeg-prebuilt#90]
Releases for 0.45.0 and 0.45.1 do not include builds for windows

**Comment by djcanard** [comment]
Yes, it would be great to have these available.

**Comment by iteufel** [comment]
I have not released a new version because nw.js does not recognize certain formats in the current version.

I'll try to take care of it this week.

**Comment by iteufel** [comment]
[https://github.com/iteufel/nwjs-ffmpeg-prebuilt/issues/91](https://github.com/iteufel/nwjs-ffmpeg-prebuilt/issues/91)
