### ISSUE TITLE
Not working anymore with 0.45.x

### ISSUE THREAD

**Issue by Jakeler** [iteufel/nwjs-ffmpeg-prebuilt#91]
Hi,
am I the only one experiencing problems with the recent version? 
Trying to open a mp4/h264 on Linux yields:
```
Error while loading the video. ERROR (4): 
DEMUXER_ERROR_NO_SUPPORTED_STREAMS: 
FFmpegDemuxer: no supported streams
```
Just like the standard nwjs libffmpeg.so.

**Comment by kartikynwa** [comment]
FWIW I just tried the latest release with nwjs-0.45.1 and it works with this RPMG game that I am playing.

**Comment by iteufel** [comment]
the current status can be found here https://github.com/nwjs/nw.js/issues/7471

**Comment by iteufel** [comment]
I have uploaded binaries for 0.46.4/5 and nw.js has fixed the issue that the video/audio formats are not recognized.
You can try http://dl.nwjs.io/live-build/nw46/20200710-003549/1fc2cba92/v0.46.5/ or wait until 0.46.5 is released.

**Comment by kartikynwa** [comment]
Thank you for your work o7

**Comment by zkrige** [comment]
0.47.3 didn't build - is there something that needs to be done to make it build?
