### ISSUE TITLE
please can you do build for 0.46.2

### ISSUE THREAD

**Issue by zkrige** [iteufel/nwjs-ffmpeg-prebuilt#94]

**Comment by asteriosgr** [comment]
0.46.3*

**Comment by hthetiot** [comment]
0.46.4*

**Comment by iteufel** [comment]
@hthetiot I have local builds but nwjs does not recognize the video/audio formats since >= 0.45.0.

**Comment by iteufel** [comment]
I have uploaded binaries for 0.46.4/5 and nw.js has fixed the issue that the video/audio formats are not recognized.
You can try http://dl.nwjs.io/live-build/nw46/20200710-003549/1fc2cba92/v0.46.5/ or wait until 0.46.5 is released.

**Comment by hthetiot** [comment]
Thank you @iteufel

**Comment by hthetiot** [comment]
0.47.0 available here for reference https://github.com/iteufel/nwjs-ffmpeg-prebuilt/releases/tag/0.47.0 I think we can close this issue.

Again thx to @iteufel
