### ISSUE TITLE
Docker or Travis build support

### ISSUE THREAD

**Issue by hthetiot** [iteufel/nwjs-ffmpeg-prebuilt#95]
I was wondering if we could add a Dockerfile to ease generating the build and even a Travis Hook to generate realease.
I have some experience with building ffmpeg, Cordova and NW.js on Windows/Mac/Linux via Travis, I think it might be doable at least the Docker part, the issue with travis might be the size and duration of the build.

Let me know you thought and if people are interested I might do a PR.

**Comment by iteufel** [comment]
@hthetiot I have created a build workflow using GitHub Actions https://github.com/iteufel/nwjs-ffmpeg-prebuilt/blob/master/.github/workflows/main.yml
But I think we could optimize it more

**Comment by hthetiot** [comment]
Related https://github.com/iteufel/nwjs-ffmpeg-prebuilt/issues/48#event-3531389084

**Comment by hthetiot** [comment]
Fixed by https://github.com/iteufel/nwjs-ffmpeg-prebuilt/blob/master/.github/workflows/main.yml I guess
