### ISSUE TITLE
I had to add "checkout_pgo_profiles": True to the custom_vars in the .glicent file of chromium on Windows for the build to work

### ISSUE THREAD

**Issue by sirisian** [iteufel/nwjs-ffmpeg-prebuilt#98]
I got the build to work after adding that. Maybe this needs to be added to the build script to add it automatically or in the docs? The errors says to add that or alternatively disable pgo. I found this where others talked about the issue: https://groups.google.com/a/chromium.org/g/chromium-dev/c/-0t4s0RlmOI

**Comment by asteriosgr** [comment]
I created a PR for it. Currently it is building under Linux x64 👍
