### ISSUE TITLE
Do I need a license if I want to use ffmpeg prebuilt dll in my product

### ISSUE THREAD

**Issue by dpjha84** [iteufel/nwjs-ffmpeg-prebuilt#99]
We want to use prebuilt ffmpeg.dll in one of our Windows desktop product which is used for commercial purpose. Do we need a license to use prebuilt ffmpeg.dll. If yes, where can we buy/apply that license and how can we use that to make sure we are good from legal stand point. Any Pointer would be highly appreciated. Thanks.

**Comment by iteufel** [comment]
Using MP3 and H.264 codecs requires you to pay attention to the patent royalties and the license of the source code. Consult a lawyer if you do not understand the licensing constraints and using patented media formats in your application. For more information about the license of the source code, check [here](https://chromium.googlesource.com/chromium/third_party/ffmpeg.git/+/master/CREDITS.chromium).


https://www.ffmpeg.org/legal.html
